// Auto-generated from the official Cambridge IGCSE Physics 0625 syllabus document.
// Do not hand-edit; regenerate from the source JSON if the syllabus changes.

export type SyllabusObjective = { id: string; text: string; type: "core" | "supplement" };
export type SyllabusGroup = { id: string; title: string; objectives: SyllabusObjective[] };
export type SyllabusTopic = { id: string; title: string; groups: SyllabusGroup[] };

export const igcsePhysicsSyllabus: SyllabusTopic[] = [
  { id: "1", title: "Motion, forces and energy", groups: [
    { id: "1.1", title: "Physical quantities and measurement techniques", objectives: [
      { id: "1.1-c1", text: "Describe the use of rulers and measuring cylinders to find a length or a volume", type: "core" },
      { id: "1.1-c2", text: "Describe how to measure a variety of time intervals using clocks and digital timers", type: "core" },
      { id: "1.1-c3", text: "Determine an average value for a small distance and for a short interval of time by measuring multiples (including the period of oscillation of a pendulum)", type: "core" },
      { id: "1.1-s1", text: "Understand that a scalar quantity has magnitude (size) only and that a vector quantity has magnitude and direction", type: "supplement" },
      { id: "1.1-s2", text: "Know that the following quantities are scalars: distance, speed, time, mass, energy and temperature", type: "supplement" },
      { id: "1.1-s3", text: "Know that the following quantities are vectors: force, weight, velocity, acceleration, momentum, electric field strength and gravitational field strength", type: "supplement" },
      { id: "1.1-s4", text: "Determine, by calculation or graphically, the resultant of two vectors at right angles, limited to forces or velocities only", type: "supplement" },
    ] },
    { id: "1.2", title: "Motion", objectives: [
      { id: "1.2-c1", text: "Define speed as distance travelled per unit time; recall and use the equation v = s/t", type: "core" },
      { id: "1.2-c2", text: "Define velocity as speed in a given direction", type: "core" },
      { id: "1.2-c3", text: "Recall and use the equation average speed = total distance travelled / total time taken", type: "core" },
      { id: "1.2-c4", text: "Sketch, plot and interpret distance-time and speed-time graphs", type: "core" },
      { id: "1.2-c5", text: "Determine, qualitatively, from given data or the shape of a distance-time graph or speed-time graph when an object is: (a) at rest (b) moving with constant speed (c) accelerating (d) decelerating", type: "core" },
      { id: "1.2-c6", text: "Calculate speed from the gradient of a straight-line section of a distance-time graph", type: "core" },
      { id: "1.2-c7", text: "Calculate the area under a speed-time graph to determine the distance travelled for motion with constant speed or constant acceleration", type: "core" },
      { id: "1.2-c8", text: "State that the acceleration of free fall g for an object near to the surface of the Earth is approximately constant and is approximately 9.8 m/s^2", type: "core" },
      { id: "1.2-s1", text: "Define acceleration as change in velocity per unit time; recall and use the equation a = delta-v / delta-t", type: "supplement" },
      { id: "1.2-s2", text: "Determine from given data or the shape of a speed-time graph when an object is moving with: (a) constant acceleration (b) changing acceleration", type: "supplement" },
      { id: "1.2-s3", text: "Calculate acceleration from the gradient of a speed-time graph", type: "supplement" },
      { id: "1.2-s4", text: "Know that a deceleration is a negative acceleration and use this in calculations", type: "supplement" },
      { id: "1.2-s5", text: "Describe the motion of objects falling in a uniform gravitational field with and without air/liquid resistance, including reference to terminal velocity", type: "supplement" },
    ] },
    { id: "1.3", title: "Mass and weight", objectives: [
      { id: "1.3-c1", text: "State that mass is a measure of the quantity of matter in an object at rest relative to the observer", type: "core" },
      { id: "1.3-c2", text: "State that weight is a gravitational force on an object that has mass", type: "core" },
      { id: "1.3-c3", text: "Define gravitational field strength as force per unit mass; recall and use the equation g = W/m and know that this is equivalent to the acceleration of free fall", type: "core" },
      { id: "1.3-c4", text: "Know that weights (and masses) may be compared using a balance", type: "core" },
      { id: "1.3-s1", text: "Describe, and use the concept of, weight as the effect of a gravitational field on a mass", type: "supplement" },
    ] },
    { id: "1.4", title: "Density", objectives: [
      { id: "1.4-c1", text: "Define density as mass per unit volume; recall and use the equation rho = m/V", type: "core" },
      { id: "1.4-c2", text: "Describe how to determine the density of a liquid, of a regularly shaped solid and of an irregularly shaped solid which sinks in a liquid (volume by displacement), including appropriate calculations", type: "core" },
      { id: "1.4-c3", text: "Determine whether an object floats based on density data", type: "core" },
      { id: "1.4-s1", text: "Determine whether one liquid will float on another liquid based on density data given that the liquids do not mix", type: "supplement" },
    ] },
    { id: "1.5.1", title: "Effects of forces", objectives: [
      { id: "1.5.1-c1", text: "Know that forces may produce changes in the size and shape of an object", type: "core" },
      { id: "1.5.1-c2", text: "Sketch, plot and interpret load-extension graphs for an elastic solid and describe the associated experimental procedures", type: "core" },
      { id: "1.5.1-c3", text: "Determine the resultant of two or more forces acting along the same straight line", type: "core" },
      { id: "1.5.1-c4", text: "Know that an object either remains at rest or continues in a straight line at constant speed unless acted on by a resultant force", type: "core" },
      { id: "1.5.1-c5", text: "State that a resultant force may change the velocity of an object by changing its direction of motion or its speed", type: "core" },
      { id: "1.5.1-c6", text: "Describe solid friction as the force between two surfaces that may impede motion and produce heating", type: "core" },
      { id: "1.5.1-c7", text: "Know that friction (drag) acts on an object moving through a liquid", type: "core" },
      { id: "1.5.1-c8", text: "Know that friction (drag) acts on an object moving through a gas (e.g. air resistance)", type: "core" },
      { id: "1.5.1-s1", text: "Define the spring constant as force per unit extension; recall and use the equation k = F/x", type: "supplement" },
      { id: "1.5.1-s2", text: "Define and use the term 'limit of proportionality' for a load-extension graph and identify this point on the graph (an understanding of the elastic limit is not required)", type: "supplement" },
      { id: "1.5.1-s3", text: "Recall and use the equation F = ma and know that the force and the acceleration are in the same direction", type: "supplement" },
      { id: "1.5.1-s4", text: "Describe, qualitatively, motion in a circular path due to a force perpendicular to the motion as: (a) speed increases if force increases, with mass and radius constant (b) radius decreases if force increases, with mass and speed constant (c) an increased mass requires an increased force to keep speed and radius constant (F = mv^2/r is not required)", type: "supplement" },
    ] },
    { id: "1.5.2", title: "Turning effect of forces", objectives: [
      { id: "1.5.2-c1", text: "Describe the moment of a force as a measure of its turning effect and give everyday examples", type: "core" },
      { id: "1.5.2-c2", text: "Define the moment of a force as moment = force x perpendicular distance from the pivot; recall and use this equation", type: "core" },
      { id: "1.5.2-c3", text: "Apply the principle of moments to situations with one force each side of the pivot, including balancing of a beam", type: "core" },
      { id: "1.5.2-c4", text: "State that, when there is no resultant force and no resultant moment, an object is in equilibrium", type: "core" },
      { id: "1.5.2-s1", text: "Apply the principle of moments to other situations, including those with more than one force each side of the pivot", type: "supplement" },
      { id: "1.5.2-s2", text: "Describe an experiment to demonstrate that there is no resultant moment on an object in equilibrium", type: "supplement" },
    ] },
    { id: "1.5.3", title: "Centre of gravity", objectives: [
      { id: "1.5.3-c1", text: "State what is meant by centre of gravity", type: "core" },
      { id: "1.5.3-c2", text: "Describe an experiment to determine the position of the centre of gravity of an irregularly shaped plane lamina", type: "core" },
      { id: "1.5.3-c3", text: "Describe, qualitatively, the effect of the position of the centre of gravity on the stability of simple objects", type: "core" },
    ] },
    { id: "1.6", title: "Momentum", objectives: [
      { id: "1.6-s1", text: "Define momentum as mass x velocity; recall and use the equation p = mv", type: "supplement" },
      { id: "1.6-s2", text: "Define impulse as force x time for which force acts; recall and use the equation impulse = F(delta-t) = delta(mv)", type: "supplement" },
      { id: "1.6-s3", text: "Apply the principle of the conservation of momentum to solve simple problems in one dimension", type: "supplement" },
      { id: "1.6-s4", text: "Define resultant force as the change in momentum per unit time; recall and use the equation F = delta-p / delta-t", type: "supplement" },
    ] },
    { id: "1.7.1", title: "Energy", objectives: [
      { id: "1.7.1-c1", text: "State that energy may be stored as kinetic, gravitational potential, chemical, elastic (strain), nuclear, electrostatic and internal (thermal)", type: "core" },
      { id: "1.7.1-c2", text: "Describe how energy is transferred between stores during events and processes, including examples of transfer by forces (mechanical work done), electrical currents (electrical work done), heating, and by electromagnetic, sound and other waves", type: "core" },
      { id: "1.7.1-c3", text: "Know the principle of the conservation of energy and apply this principle to simple examples including the interpretation of simple flow diagrams", type: "core" },
      { id: "1.7.1-s1", text: "Recall and use the equation for kinetic energy Ek = (1/2)mv^2", type: "supplement" },
      { id: "1.7.1-s2", text: "Recall and use the equation for the change in gravitational potential energy delta-Ep = mg(delta-h)", type: "supplement" },
      { id: "1.7.1-s3", text: "Know the principle of the conservation of energy and apply this principle to complex examples involving multiple stages, including the interpretation of Sankey diagrams", type: "supplement" },
    ] },
    { id: "1.7.2", title: "Work", objectives: [
      { id: "1.7.2-c1", text: "Understand that mechanical or electrical work done is equal to the energy transferred", type: "core" },
      { id: "1.7.2-c2", text: "Recall and use the equation for mechanical working W = Fd = delta-E", type: "core" },
    ] },
    { id: "1.7.3", title: "Energy resources", objectives: [
      { id: "1.7.3-c1", text: "Describe how useful energy may be obtained, or electrical power generated, from: (a) chemical energy stored in fossil fuels (b) chemical energy stored in biofuels (c) water, including the energy stored in waves, in tides and in water behind hydroelectric dams (d) geothermal resources (e) nuclear fuel (f) light from the Sun to generate electrical power (solar cells) (g) infrared and other electromagnetic waves from the Sun to heat water (solar panels) and be the source of wind energy, including references to a boiler, turbine and generator where they are used", type: "core" },
      { id: "1.7.3-c2", text: "Describe advantages and disadvantages of each method in terms of renewability, availability, reliability, scale and environmental impact", type: "core" },
      { id: "1.7.3-c3", text: "Understand, qualitatively, the concept of efficiency of energy transfer", type: "core" },
      { id: "1.7.3-s1", text: "Know that radiation from the Sun is the main source of energy for all our energy resources except geothermal, nuclear and tidal", type: "supplement" },
      { id: "1.7.3-s2", text: "Know that energy is released by nuclear fusion in the Sun", type: "supplement" },
      { id: "1.7.3-s3", text: "Know that research is being carried out to investigate how energy released by nuclear fusion can be used to produce electrical energy on a large scale", type: "supplement" },
      { id: "1.7.3-s4", text: "Define efficiency as: (a) %efficiency = (useful energy output)/(total energy input) x 100% (b) %efficiency = (useful power output)/(total power input) x 100%; recall and use these equations", type: "supplement" },
    ] },
    { id: "1.7.4", title: "Power", objectives: [
      { id: "1.7.4-c1", text: "Define power as work done per unit time and also as energy transferred per unit time; recall and use the equations (a) P = W/t (b) P = delta-E/t", type: "core" },
    ] },
    { id: "1.8", title: "Pressure", objectives: [
      { id: "1.8-c1", text: "Define pressure as force per unit area; recall and use the equation p = F/A", type: "core" },
      { id: "1.8-c2", text: "Describe how pressure varies with force and area in the context of everyday examples", type: "core" },
      { id: "1.8-c3", text: "Describe, qualitatively, how the pressure beneath the surface of a liquid changes with depth and density of the liquid", type: "core" },
      { id: "1.8-s1", text: "Recall and use the equation for the change in pressure beneath the surface of a liquid delta-p = rho x g x delta-h", type: "supplement" },
    ] },
  ] },
  { id: "2", title: "Thermal physics", groups: [
    { id: "2.1.1", title: "States of matter", objectives: [
      { id: "2.1.1-c1", text: "Know the distinguishing properties of solids, liquids and gases", type: "core" },
      { id: "2.1.1-c2", text: "Know the terms for the changes in state between solids, liquids and gases (gas to solid and solid to gas transfers are not required)", type: "core" },
    ] },
    { id: "2.1.2", title: "Particle model", objectives: [
      { id: "2.1.2-c1", text: "Describe the particle structure of solids, liquids and gases in terms of the arrangement, separation and motion of the particles and represent these states using simple particle diagrams", type: "core" },
      { id: "2.1.2-c2", text: "Describe the relationship between the motion of particles and temperature, including the idea that there is a lowest possible temperature (-273 degrees C), known as absolute zero, where the particles have least kinetic energy", type: "core" },
      { id: "2.1.2-c3", text: "Describe the pressure and the changes in pressure of a gas in terms of the motion of its particles and their collisions with a surface", type: "core" },
      { id: "2.1.2-c4", text: "Know that the random motion of microscopic particles in a suspension is evidence for the kinetic particle model of matter", type: "core" },
      { id: "2.1.2-c5", text: "Describe and explain this motion (sometimes known as Brownian motion) in terms of random collisions between the microscopic particles in a suspension and the particles of the gas or liquid", type: "core" },
      { id: "2.1.2-s1", text: "Know that the forces and distances between particles (atoms, molecules, ions and electrons) and the motion of the particles affects the properties of solids, liquids and gases", type: "supplement" },
      { id: "2.1.2-s2", text: "Describe the pressure and the changes in pressure of a gas in terms of the forces exerted by particles colliding with surfaces, creating a force per unit area", type: "supplement" },
      { id: "2.1.2-s3", text: "Know that microscopic particles may be moved by collisions with light fast-moving molecules and correctly use the terms atoms or molecules as distinct from microscopic particles", type: "supplement" },
    ] },
    { id: "2.1.3", title: "Gases and the absolute scale of temperature", objectives: [
      { id: "2.1.3-c1", text: "Describe qualitatively, in terms of particles, the effect on the pressure of a fixed mass of gas of: (a) a change of temperature at constant volume (b) a change of volume at constant temperature", type: "core" },
      { id: "2.1.3-c2", text: "Convert temperatures between kelvin and degrees Celsius; recall and use the equation T (in K) = theta (in degrees C) + 273", type: "core" },
      { id: "2.1.3-s1", text: "Recall and use the equation pV = constant for a fixed mass of gas at constant temperature, including a graphical representation of this relationship", type: "supplement" },
    ] },
    { id: "2.2.1", title: "Thermal expansion of solids, liquids and gases", objectives: [
      { id: "2.2.1-c1", text: "Describe, qualitatively, the thermal expansion of solids, liquids and gases at constant pressure", type: "core" },
      { id: "2.2.1-c2", text: "Describe some of the everyday applications and consequences of thermal expansion", type: "core" },
      { id: "2.2.1-s1", text: "Explain, in terms of the motion and arrangement of particles, the relative order of magnitudes of the expansion of solids, liquids and gases as their temperatures rise", type: "supplement" },
    ] },
    { id: "2.2.2", title: "Specific heat capacity", objectives: [
      { id: "2.2.2-c1", text: "Know that a rise in the temperature of an object increases its internal energy", type: "core" },
      { id: "2.2.2-s1", text: "Describe an increase in temperature of an object in terms of an increase in the average kinetic energies of all of the particles in the object", type: "supplement" },
      { id: "2.2.2-s2", text: "Define specific heat capacity as the energy required per unit mass per unit temperature increase; recall and use the equation c = delta-E / (m x delta-theta)", type: "supplement" },
      { id: "2.2.2-s3", text: "Describe experiments to measure the specific heat capacity of a solid and a liquid", type: "supplement" },
    ] },
    { id: "2.2.3", title: "Melting, boiling and evaporation", objectives: [
      { id: "2.2.3-c1", text: "Describe melting and boiling in terms of energy input without a change in temperature", type: "core" },
      { id: "2.2.3-c2", text: "Know the melting and boiling temperatures for water at standard atmospheric pressure", type: "core" },
      { id: "2.2.3-c3", text: "Describe condensation and solidification in terms of particles", type: "core" },
      { id: "2.2.3-c4", text: "Describe evaporation in terms of the escape of more-energetic particles from the surface of a liquid", type: "core" },
      { id: "2.2.3-c5", text: "Know that evaporation causes cooling of a liquid", type: "core" },
      { id: "2.2.3-s1", text: "Describe the differences between boiling and evaporation", type: "supplement" },
      { id: "2.2.3-s2", text: "Describe how temperature, surface area and air movement over a surface affect evaporation", type: "supplement" },
      { id: "2.2.3-s3", text: "Explain the cooling of an object in contact with an evaporating liquid", type: "supplement" },
    ] },
    { id: "2.3.1", title: "Conduction", objectives: [
      { id: "2.3.1-c1", text: "Describe experiments to demonstrate the properties of good thermal conductors and bad thermal conductors (thermal insulators)", type: "core" },
      { id: "2.3.1-s1", text: "Describe thermal conduction in all solids in terms of atomic or molecular lattice vibrations and also in terms of the movement of free (delocalised) electrons in metallic conductors", type: "supplement" },
      { id: "2.3.1-s2", text: "Describe, in terms of particles, why thermal conduction is bad in gases and most liquids", type: "supplement" },
      { id: "2.3.1-s3", text: "Know that there are many solids that conduct thermal energy better than thermal insulators but do so less well than good thermal conductors", type: "supplement" },
    ] },
    { id: "2.3.2", title: "Convection", objectives: [
      { id: "2.3.2-c1", text: "Know that convection is an important method of thermal energy transfer in liquids and gases", type: "core" },
      { id: "2.3.2-c2", text: "Explain convection in liquids and gases in terms of density changes and describe experiments to illustrate convection", type: "core" },
    ] },
    { id: "2.3.3", title: "Radiation", objectives: [
      { id: "2.3.3-c1", text: "Know that thermal radiation is infrared radiation and that all objects emit this radiation", type: "core" },
      { id: "2.3.3-c2", text: "Know that thermal energy transfer by thermal radiation does not require a medium", type: "core" },
      { id: "2.3.3-c3", text: "Describe the effect of surface colour (black or white) and texture (dull or shiny) on the emission, absorption and reflection of infrared radiation", type: "core" },
      { id: "2.3.3-s1", text: "Know that for an object to be at a constant temperature it needs to transfer energy away from the object at the same rate that it receives energy", type: "supplement" },
      { id: "2.3.3-s2", text: "Know what happens to an object if the rate at which it receives energy is less or more than the rate at which it transfers energy away from the object", type: "supplement" },
      { id: "2.3.3-s3", text: "Know how the temperature of the Earth is affected by factors controlling the balance between incoming radiation and radiation emitted from the Earth's surface", type: "supplement" },
      { id: "2.3.3-s4", text: "Describe experiments to distinguish between good and bad emitters of infrared radiation", type: "supplement" },
      { id: "2.3.3-s5", text: "Describe experiments to distinguish between good and bad absorbers of infrared radiation", type: "supplement" },
      { id: "2.3.3-s6", text: "Describe how the rate of emission of radiation depends on the surface temperature and surface area of an object", type: "supplement" },
    ] },
    { id: "2.3.4", title: "Consequences of thermal energy transfer", objectives: [
      { id: "2.3.4-c1", text: "Explain some of the basic everyday applications and consequences of conduction, convection and radiation, including: (a) heating objects such as kitchen pans (b) heating a room by convection", type: "core" },
      { id: "2.3.4-s1", text: "Explain some of the complex applications and consequences of conduction, convection and radiation where more than one type of thermal energy transfer is significant, including: (a) a fire burning wood or coal (b) a radiator in a car", type: "supplement" },
    ] },
  ] },
  { id: "3", title: "Waves", groups: [
    { id: "3.1", title: "General properties of waves", objectives: [
      { id: "3.1-c1", text: "Know that waves transfer energy without transferring matter", type: "core" },
      { id: "3.1-c2", text: "Describe what is meant by wave motion as illustrated by vibrations in ropes and springs, and by experiments using water waves", type: "core" },
      { id: "3.1-c3", text: "Describe the features of a wave in terms of wavefront, wavelength, frequency, crest (peak), trough, amplitude and wave speed", type: "core" },
      { id: "3.1-c4", text: "Recall and use the equation for wave speed v = f(lambda)", type: "core" },
      { id: "3.1-c5", text: "Know that for a transverse wave, the direction of vibration is at right angles to the direction of propagation and understand that electromagnetic radiation, water waves and seismic S-waves (secondary) can be modelled as transverse", type: "core" },
      { id: "3.1-c6", text: "Know that for a longitudinal wave, the direction of vibration is parallel to the direction of propagation and understand that sound waves and seismic P-waves (primary) can be modelled as longitudinal", type: "core" },
      { id: "3.1-c7", text: "Describe how waves can undergo: (a) reflection at a plane surface (b) refraction due to a change in speed (c) diffraction through a narrow gap", type: "core" },
      { id: "3.1-c8", text: "Describe the use of a ripple tank to show: (a) reflection at a plane surface (b) refraction due to a change in speed caused by a change in depth (c) diffraction due to a gap (d) diffraction due to an edge", type: "core" },
      { id: "3.1-s1", text: "Describe how wavelength and gap size affects diffraction through a gap", type: "supplement" },
      { id: "3.1-s2", text: "Describe how wavelength affects diffraction at an edge", type: "supplement" },
    ] },
    { id: "3.2.1", title: "Reflection of light", objectives: [
      { id: "3.2.1-c1", text: "Define and use the terms normal, angle of incidence and angle of reflection", type: "core" },
      { id: "3.2.1-c2", text: "Describe the formation of an optical image by a plane mirror and give its characteristics, i.e. same size, same distance from mirror, virtual", type: "core" },
      { id: "3.2.1-c3", text: "State that for reflection, the angle of incidence is equal to the angle of reflection; recall and use this relationship", type: "core" },
      { id: "3.2.1-s1", text: "Use simple constructions, measurements and calculations for reflection by plane mirrors", type: "supplement" },
    ] },
    { id: "3.2.2", title: "Refraction of light", objectives: [
      { id: "3.2.2-c1", text: "Define and use the terms normal, angle of incidence and angle of refraction", type: "core" },
      { id: "3.2.2-c2", text: "Describe an experiment to show refraction of light by transparent blocks of different shapes", type: "core" },
      { id: "3.2.2-c3", text: "Describe the passage of light through a transparent material (limited to the boundaries between two mediums only)", type: "core" },
      { id: "3.2.2-c4", text: "State the meaning of critical angle", type: "core" },
      { id: "3.2.2-c5", text: "Describe internal reflection and total internal reflection using both experimental and everyday examples", type: "core" },
      { id: "3.2.2-s1", text: "Define refractive index, n, as the ratio of the speeds of a wave in two different regions", type: "supplement" },
      { id: "3.2.2-s2", text: "Recall and use the equation n = sin(i) / sin(r)", type: "supplement" },
      { id: "3.2.2-s3", text: "Recall and use the equation n = 1 / sin(c)", type: "supplement" },
      { id: "3.2.2-s4", text: "Describe the use of optical fibres, particularly in telecommunications", type: "supplement" },
    ] },
    { id: "3.2.3", title: "Thin lenses", objectives: [
      { id: "3.2.3-c1", text: "Describe the action of thin converging and thin diverging lenses on a parallel beam of light", type: "core" },
      { id: "3.2.3-c2", text: "Define and use the terms focal length, principal axis and principal focus (focal point)", type: "core" },
      { id: "3.2.3-c3", text: "Draw and use ray diagrams for the formation of a real image by a converging lens", type: "core" },
      { id: "3.2.3-c4", text: "Describe the characteristics of an image using the terms enlarged/same size/diminished, upright/inverted and real/virtual", type: "core" },
      { id: "3.2.3-c5", text: "Know that a virtual image is formed when diverging rays are extrapolated backwards and does not form a visible projection on a screen", type: "core" },
      { id: "3.2.3-s1", text: "Draw and use ray diagrams for the formation of a virtual image by a converging lens", type: "supplement" },
      { id: "3.2.3-s2", text: "Describe the use of a single lens as a magnifying glass", type: "supplement" },
      { id: "3.2.3-s3", text: "Describe the use of converging and diverging lenses to correct long-sightedness and short-sightedness", type: "supplement" },
    ] },
    { id: "3.2.4", title: "Dispersion of light", objectives: [
      { id: "3.2.4-c1", text: "Describe the dispersion of light as illustrated by the refraction of white light by a glass prism", type: "core" },
      { id: "3.2.4-c2", text: "Know the traditional seven colours of the visible spectrum in order of frequency and in order of wavelength", type: "core" },
      { id: "3.2.4-s1", text: "Recall that visible light of a single frequency is described as monochromatic", type: "supplement" },
    ] },
    { id: "3.3", title: "Electromagnetic spectrum", objectives: [
      { id: "3.3-c1", text: "Know the main regions of the electromagnetic spectrum in order of frequency and in order of wavelength", type: "core" },
      { id: "3.3-c2", text: "Know that all electromagnetic waves travel at the same high speed in a vacuum", type: "core" },
      { id: "3.3-c3", text: "Describe typical uses of the different regions of the electromagnetic spectrum including: (a) radio waves; radio and television transmissions, astronomy, radio frequency identification (RFID) (b) microwaves; satellite television, mobile phones (cell phones), microwave ovens (c) infrared; electric grills, short range communications such as remote controllers for televisions, intruder alarms, thermal imaging, optical fibres (d) visible light; vision, photography, illumination (e) ultraviolet; security marking, detecting fake bank notes, sterilising water (f) X-rays; medical scanning, security scanners (g) gamma rays; sterilising food and medical equipment, detection of cancer and its treatment", type: "core" },
      { id: "3.3-c4", text: "Describe the harmful effects on people of excessive exposure to electromagnetic radiation, including: (a) microwaves; internal heating of body cells (b) infrared; skin burns (c) ultraviolet; damage to surface cells and eyes, leading to skin cancer and eye conditions (d) X-rays and gamma rays; mutation or damage to cells in the body", type: "core" },
      { id: "3.3-c5", text: "Know that communication with artificial satellites is mainly by microwaves: (a) some satellite phones use low orbit artificial satellites (b) some satellite phones and direct broadcast satellite television use geostationary satellites", type: "core" },
      { id: "3.3-s1", text: "Know that the speed of electromagnetic waves in a vacuum is 3.0 x 10^8 m/s and is approximately the same in air", type: "supplement" },
      { id: "3.3-s2", text: "Know that many important systems of communications rely on electromagnetic radiation including: (a) mobile phones (cell phones) and wireless internet use microwaves because microwaves can penetrate some walls and only require a short aerial for transmission and reception (b) Bluetooth uses radio waves because radio waves pass through walls but the signal is weakened on doing so (c) optical fibres (visible light or infrared) are used for cable television and high-speed broadband because glass is transparent to visible light and some infrared; visible light and short wavelength infrared can carry high rates of data", type: "supplement" },
      { id: "3.3-s3", text: "Know the difference between a digital and analogue signal", type: "supplement" },
      { id: "3.3-s4", text: "Know that a sound can be transmitted as a digital or analogue signal", type: "supplement" },
      { id: "3.3-s5", text: "Explain the benefits of digital signalling including increased rate of transmission of data and increased range due to accurate signal regeneration", type: "supplement" },
    ] },
    { id: "3.4", title: "Sound", objectives: [
      { id: "3.4-c1", text: "Describe the production of sound by vibrating sources", type: "core" },
      { id: "3.4-c2", text: "Describe the longitudinal nature of sound waves", type: "core" },
      { id: "3.4-c3", text: "State the approximate range of frequencies audible to humans as 20 Hz to 20000 Hz", type: "core" },
      { id: "3.4-c4", text: "Know that a medium is needed to transmit sound waves", type: "core" },
      { id: "3.4-c5", text: "Know that the speed of sound in air is approximately 330-350 m/s", type: "core" },
      { id: "3.4-c6", text: "Describe a method involving a measurement of distance and time for determining the speed of sound in air", type: "core" },
      { id: "3.4-c7", text: "Describe how changes in amplitude and frequency affect the loudness and pitch of sound waves", type: "core" },
      { id: "3.4-c8", text: "Describe an echo as the reflection of sound waves", type: "core" },
      { id: "3.4-c9", text: "Define ultrasound as sound with a frequency higher than 20 kHz", type: "core" },
      { id: "3.4-s1", text: "Describe compression and rarefaction", type: "supplement" },
      { id: "3.4-s2", text: "Know that, in general, sound travels faster in solids than in liquids and faster in liquids than in gases", type: "supplement" },
      { id: "3.4-s3", text: "Describe the uses of ultrasound in non-destructive testing of materials, medical scanning of soft tissue and sonar including calculation of depth or distance from time and wave speed", type: "supplement" },
    ] },
  ] },
  { id: "4", title: "Electricity and magnetism", groups: [
    { id: "4.1", title: "Simple phenomena of magnetism", objectives: [
      { id: "4.1-c1", text: "Describe the forces between magnetic poles and between magnets and magnetic materials, including the use of the terms north pole (N pole), south pole (S pole), attraction and repulsion, magnetised and unmagnetised", type: "core" },
      { id: "4.1-c2", text: "Describe induced magnetism", type: "core" },
      { id: "4.1-c3", text: "State the differences between the properties of temporary magnets (made of soft iron) and the properties of permanent magnets (made of steel)", type: "core" },
      { id: "4.1-c4", text: "State the difference between magnetic and non-magnetic materials", type: "core" },
      { id: "4.1-c5", text: "Describe a magnetic field as a region in which a magnetic pole experiences a force", type: "core" },
      { id: "4.1-c6", text: "Draw the pattern and direction of magnetic field lines around a bar magnet", type: "core" },
      { id: "4.1-c7", text: "State that the direction of a magnetic field at a point is the direction of the force on the N pole of a magnet at that point", type: "core" },
      { id: "4.1-c8", text: "Describe the plotting of magnetic field lines with a compass or iron filings and the use of a compass to determine the direction of the magnetic field", type: "core" },
      { id: "4.1-c9", text: "Describe the uses of permanent magnets and electromagnets", type: "core" },
      { id: "4.1-s1", text: "Explain that magnetic forces are due to interactions between magnetic fields", type: "supplement" },
      { id: "4.1-s2", text: "Know that the relative strength of a magnetic field is represented by the spacing of the magnetic field lines", type: "supplement" },
    ] },
    { id: "4.2.1", title: "Electric charge", objectives: [
      { id: "4.2.1-c1", text: "State that there are positive and negative charges", type: "core" },
      { id: "4.2.1-c2", text: "State that positive charges repel other positive charges, negative charges repel other negative charges, but positive charges attract negative charges", type: "core" },
      { id: "4.2.1-c3", text: "Describe simple experiments to show the production of electrostatic charges by friction and to show the detection of electrostatic charges", type: "core" },
      { id: "4.2.1-c4", text: "Explain that charging of solids by friction involves only a transfer of negative charge (electrons)", type: "core" },
      { id: "4.2.1-c5", text: "Describe an experiment to distinguish between electrical conductors and insulators", type: "core" },
      { id: "4.2.1-c6", text: "Recall and use a simple electron model to explain the difference between electrical conductors and insulators and give typical examples", type: "core" },
      { id: "4.2.1-s1", text: "State that charge is measured in coulombs", type: "supplement" },
      { id: "4.2.1-s2", text: "Describe an electric field as a region in which an electric charge experiences a force", type: "supplement" },
      { id: "4.2.1-s3", text: "State that the direction of an electric field at a point is the direction of the force on a positive charge at that point", type: "supplement" },
      { id: "4.2.1-s4", text: "Describe simple electric field patterns, including the direction of the field: (a) around a point charge (b) around a charged conducting sphere (c) between two oppositely charged parallel conducting plates (end effects will not be examined)", type: "supplement" },
    ] },
    { id: "4.2.2", title: "Electric current", objectives: [
      { id: "4.2.2-c1", text: "Know that electric current is related to the flow of charge", type: "core" },
      { id: "4.2.2-c2", text: "Describe the use of ammeters (analogue and digital) with different ranges", type: "core" },
      { id: "4.2.2-c3", text: "Describe electrical conduction in metals in terms of the movement of free electrons", type: "core" },
      { id: "4.2.2-c4", text: "Know the difference between direct current (d.c.) and alternating current (a.c.)", type: "core" },
      { id: "4.2.2-s1", text: "Define electric current as the charge passing a point per unit time; recall and use the equation I = Q/t", type: "supplement" },
      { id: "4.2.2-s2", text: "State that conventional current is from positive to negative and that the flow of free electrons is from negative to positive", type: "supplement" },
    ] },
    { id: "4.2.3", title: "Electromotive force and potential difference", objectives: [
      { id: "4.2.3-c1", text: "Define electromotive force (e.m.f.) as the electrical work done by a source in moving a unit charge around a complete circuit", type: "core" },
      { id: "4.2.3-c2", text: "Know that e.m.f. is measured in volts (V)", type: "core" },
      { id: "4.2.3-c3", text: "Define potential difference (p.d.) as the work done by a unit charge passing through a component", type: "core" },
      { id: "4.2.3-c4", text: "Know that the p.d. between two points is measured in volts (V)", type: "core" },
      { id: "4.2.3-c5", text: "Describe the use of voltmeters (analogue and digital) with different ranges", type: "core" },
      { id: "4.2.3-s1", text: "Recall and use the equation for e.m.f. E = W/Q", type: "supplement" },
      { id: "4.2.3-s2", text: "Recall and use the equation for p.d. V = W/Q", type: "supplement" },
    ] },
    { id: "4.2.4", title: "Resistance", objectives: [
      { id: "4.2.4-c1", text: "Recall and use the equation for resistance R = V/I", type: "core" },
      { id: "4.2.4-c2", text: "Describe an experiment to determine resistance using a voltmeter and an ammeter and do the appropriate calculations", type: "core" },
      { id: "4.2.4-c3", text: "State, qualitatively, the relationship of the resistance of a metallic wire to its length and to its cross-sectional area", type: "core" },
      { id: "4.2.4-s1", text: "Sketch and explain the current-voltage graphs for a resistor of constant resistance, a filament lamp and a diode", type: "supplement" },
      { id: "4.2.4-s2", text: "Recall and use the following relationship for a metallic electrical conductor: (a) resistance is directly proportional to length (b) resistance is inversely proportional to cross-sectional area", type: "supplement" },
    ] },
    { id: "4.2.5", title: "Electrical energy and electrical power", objectives: [
      { id: "4.2.5-c1", text: "Understand that electric circuits transfer energy from a source of electrical energy, such as an electrical cell or mains supply, to the circuit components and then into the surroundings", type: "core" },
      { id: "4.2.5-c2", text: "Recall and use the equation for electrical power P = IV", type: "core" },
      { id: "4.2.5-c3", text: "Recall and use the equation for electrical energy E = IVt", type: "core" },
      { id: "4.2.5-c4", text: "Define the kilowatt-hour (kWh) and calculate the cost of using electrical appliances where the energy unit is the kWh", type: "core" },
    ] },
    { id: "4.3.1", title: "Circuit diagrams and circuit components", objectives: [
      { id: "4.3.1-c1", text: "Draw and interpret circuit diagrams containing cells, batteries, power supplies, generators, potential dividers, switches, resistors (fixed and variable), heaters, thermistors (NTC only), light-dependent resistors (LDRs), lamps, motors, bells, ammeters, voltmeters, magnetising coils, transformers, fuses and relays and know how these components behave in the circuit", type: "core" },
      { id: "4.3.1-s1", text: "Draw and interpret circuit diagrams containing diodes and light-emitting diodes (LEDs) and know how these components behave in the circuit", type: "supplement" },
    ] },
    { id: "4.3.2", title: "Series and parallel circuits", objectives: [
      { id: "4.3.2-c1", text: "Know that the current at every point in a series circuit is the same", type: "core" },
      { id: "4.3.2-c2", text: "Know how to construct and use series and parallel circuits", type: "core" },
      { id: "4.3.2-c3", text: "Calculate the combined e.m.f. of several sources in series", type: "core" },
      { id: "4.3.2-c4", text: "Calculate the combined resistance of two or more resistors in series", type: "core" },
      { id: "4.3.2-c5", text: "State that, for a parallel circuit, the current from the source is larger than the current in each branch", type: "core" },
      { id: "4.3.2-c6", text: "State that the combined resistance of two resistors in parallel is less than that of either resistor by itself", type: "core" },
      { id: "4.3.2-c7", text: "State the advantages of connecting lamps in parallel in a lighting circuit", type: "core" },
      { id: "4.3.2-s1", text: "Recall and use in calculations, the fact that: (a) the sum of the currents entering a junction in a parallel circuit is equal to the sum of the currents that leave the junction (b) the total p.d. across the components in a series circuit is equal to the sum of the individual p.d.s across each component (c) the p.d. across an arrangement of parallel resistances is the same as the p.d. across one branch in the arrangement of the parallel resistances", type: "supplement" },
      { id: "4.3.2-s2", text: "Explain that the sum of the currents into a junction is the same as the sum of the currents out of the junction", type: "supplement" },
      { id: "4.3.2-s3", text: "Calculate the combined resistance of two resistors in parallel", type: "supplement" },
    ] },
    { id: "4.3.3", title: "Action and use of circuit components", objectives: [
      { id: "4.3.3-c1", text: "Know that the p.d. across an electrical conductor increases as its resistance increases for a constant current", type: "core" },
      { id: "4.3.3-s1", text: "Describe the action of a variable potential divider", type: "supplement" },
      { id: "4.3.3-s2", text: "Recall and use the equation for two resistors used as a potential divider R1/R2 = V1/V2", type: "supplement" },
    ] },
    { id: "4.4", title: "Electrical safety", objectives: [
      { id: "4.4-c1", text: "State the hazards of: (a) damaged insulation (b) overheating cables (c) damp conditions (d) excess current from overloading of plugs, extension leads, single and multiple sockets, when using a mains supply", type: "core" },
      { id: "4.4-c2", text: "Know that a mains circuit consists of a live wire (line wire), a neutral wire and an earth wire and explain why a switch must be connected to the live wire for the circuit to be switched off safely", type: "core" },
      { id: "4.4-c3", text: "Explain the use and operation of trip switches and fuses and choose appropriate fuse ratings and trip switch settings", type: "core" },
      { id: "4.4-c4", text: "Explain why the outer casing of an electrical appliance must be either non-conducting (double-insulated) or earthed", type: "core" },
      { id: "4.4-c5", text: "State that a fuse without an earth wire protects the circuit and the cabling for a double-insulated appliance", type: "core" },
    ] },
    { id: "4.5.1", title: "Electromagnetic induction", objectives: [
      { id: "4.5.1-c1", text: "Know that a conductor moving across a magnetic field or a changing magnetic field linking with a conductor can induce an e.m.f. in the conductor", type: "core" },
      { id: "4.5.1-c2", text: "Describe an experiment to demonstrate electromagnetic induction", type: "core" },
      { id: "4.5.1-c3", text: "State the factors affecting the magnitude of an induced e.m.f.", type: "core" },
      { id: "4.5.1-s1", text: "Know that the direction of an induced e.m.f. opposes the change causing it", type: "supplement" },
      { id: "4.5.1-s2", text: "State and use the relative directions of force, field and induced current", type: "supplement" },
    ] },
    { id: "4.5.2", title: "The a.c. generator", objectives: [
      { id: "4.5.2-s1", text: "Describe a simple form of a.c. generator (rotating coil or rotating magnet) and the use of slip rings and brushes where needed", type: "supplement" },
      { id: "4.5.2-s2", text: "Sketch and interpret graphs of e.m.f. against time for simple a.c. generators and relate the position of the generator coil to the peaks, troughs and zeros of the e.m.f.", type: "supplement" },
    ] },
    { id: "4.5.3", title: "Magnetic effect of a current", objectives: [
      { id: "4.5.3-c1", text: "Describe the pattern and direction of the magnetic field due to currents in straight wires and in solenoids", type: "core" },
      { id: "4.5.3-c2", text: "Describe an experiment to identify the pattern of the magnetic field (including direction) due to currents in straight wires and in solenoids", type: "core" },
      { id: "4.5.3-c3", text: "Describe how the magnetic effect of a current is used in relays and loudspeakers and give examples of their application", type: "core" },
      { id: "4.5.3-s1", text: "State the qualitative variation of the strength of the magnetic field around straight wires and solenoids", type: "supplement" },
      { id: "4.5.3-s2", text: "Describe the effect on the magnetic field around straight wires and solenoids of changing the magnitude and direction of the current", type: "supplement" },
    ] },
    { id: "4.5.4", title: "Force on a current-carrying conductor", objectives: [
      { id: "4.5.4-c1", text: "Describe an experiment to show that a force acts on a current-carrying conductor in a magnetic field, including the effect of reversing: (a) the current (b) the direction of the field", type: "core" },
      { id: "4.5.4-s1", text: "Recall and use the relative directions of force, magnetic field and current", type: "supplement" },
      { id: "4.5.4-s2", text: "Determine the direction of the force on beams of charged particles in a magnetic field", type: "supplement" },
    ] },
    { id: "4.5.5", title: "The d.c. motor", objectives: [
      { id: "4.5.5-c1", text: "Know that a current-carrying coil in a magnetic field may experience a turning effect and that the turning effect is increased by increasing: (a) the number of turns on the coil (b) the current (c) the strength of the magnetic field", type: "core" },
      { id: "4.5.5-s1", text: "Describe the operation of an electric motor, including the action of a split-ring commutator and brushes", type: "supplement" },
    ] },
    { id: "4.5.6", title: "The transformer", objectives: [
      { id: "4.5.6-c1", text: "Describe the construction of a simple transformer with a soft-iron core, as used for voltage transformations", type: "core" },
      { id: "4.5.6-c2", text: "Use the terms primary, secondary, step-up and step-down", type: "core" },
      { id: "4.5.6-c3", text: "Recall and use the equation Vp/Vs = Np/Ns where p and s refer to primary and secondary", type: "core" },
      { id: "4.5.6-c4", text: "Describe the use of transformers in high-voltage transmission of electricity", type: "core" },
      { id: "4.5.6-c5", text: "State the advantages of high-voltage transmission", type: "core" },
      { id: "4.5.6-s1", text: "Explain the principle of operation of a simple iron-cored transformer", type: "supplement" },
      { id: "4.5.6-s2", text: "Recall and use the equation for 100% efficiency in a transformer IpVp = IsVs where p and s refer to primary and secondary", type: "supplement" },
      { id: "4.5.6-s3", text: "Recall and use the equation P = I^2R to explain why power losses in cables are smaller when the voltage is greater", type: "supplement" },
    ] },
  ] },
  { id: "5", title: "Nuclear physics", groups: [
    { id: "5.1.1", title: "The atom", objectives: [
      { id: "5.1.1-c1", text: "Describe the structure of an atom in terms of a positively charged nucleus and negatively charged electrons in orbit around the nucleus", type: "core" },
      { id: "5.1.1-c2", text: "Know how atoms may form positive ions by losing electrons or form negative ions by gaining electrons", type: "core" },
      { id: "5.1.1-s1", text: "Describe how the scattering of alpha (alpha) particles by a sheet of thin metal supports the nuclear model of the atom, by providing evidence for: (a) a very small nucleus surrounded by mostly empty space (b) a nucleus containing most of the mass of the atom (c) a nucleus that is positively charged", type: "supplement" },
    ] },
    { id: "5.1.2", title: "The nucleus", objectives: [
      { id: "5.1.2-c1", text: "Describe the composition of the nucleus in terms of protons and neutrons", type: "core" },
      { id: "5.1.2-c2", text: "State the relative charges of protons, neutrons and electrons as +1, 0 and -1 respectively", type: "core" },
      { id: "5.1.2-c3", text: "Define the terms proton number (atomic number) Z and nucleon number (mass number) A and be able to calculate the number of neutrons in a nucleus", type: "core" },
      { id: "5.1.2-c4", text: "Use the nuclide notation (A over Z)X", type: "core" },
      { id: "5.1.2-c5", text: "Explain what is meant by an isotope and state that an element may have more than one isotope", type: "core" },
      { id: "5.1.2-s1", text: "Describe the processes of nuclear fission and nuclear fusion as the splitting or joining of nuclei, to include the nuclide equation and qualitative description of mass and energy changes without values", type: "supplement" },
      { id: "5.1.2-s2", text: "Know the relationship between the proton number and the relative charge on a nucleus", type: "supplement" },
      { id: "5.1.2-s3", text: "Know the relationship between the nucleon number and the relative mass of a nucleus", type: "supplement" },
    ] },
    { id: "5.2.1", title: "Detection of radioactivity", objectives: [
      { id: "5.2.1-c1", text: "Know what is meant by background radiation", type: "core" },
      { id: "5.2.1-c2", text: "Know the sources that make a significant contribution to background radiation including: (a) radon gas (in the air) (b) rocks and buildings (c) food and drink (d) cosmic rays", type: "core" },
      { id: "5.2.1-c3", text: "Know that ionising nuclear radiation can be measured using a detector connected to a counter", type: "core" },
      { id: "5.2.1-c4", text: "Use count rate measured in counts/s or counts/minute", type: "core" },
      { id: "5.2.1-s1", text: "Use measurements of background radiation to determine a corrected count rate", type: "supplement" },
    ] },
    { id: "5.2.2", title: "The three types of nuclear emission", objectives: [
      { id: "5.2.2-c1", text: "Describe the emission of radiation from a nucleus as spontaneous and random in direction", type: "core" },
      { id: "5.2.2-c2", text: "Identify alpha (alpha), beta (beta) and gamma (gamma) emissions from the nucleus by recalling: (a) their nature (b) their relative ionising effects (c) their relative penetrating abilities (beta+ are not included, beta-particles will be taken to refer to beta-)", type: "core" },
      { id: "5.2.2-s1", text: "Describe the deflection of alpha-particles, beta-particles and gamma-radiation in electric fields and magnetic fields", type: "supplement" },
      { id: "5.2.2-s2", text: "Explain their relative ionising effects with reference to: (a) kinetic energy (b) electric charge", type: "supplement" },
    ] },
    { id: "5.2.3", title: "Radioactive decay", objectives: [
      { id: "5.2.3-c1", text: "Know that radioactive decay is a change in an unstable nucleus that can result in the emission of alpha-particles or beta-particles and/or gamma-radiation and know that these changes are spontaneous and random", type: "core" },
      { id: "5.2.3-c2", text: "State that during alpha-decay or beta-decay, the nucleus changes to that of a different element", type: "core" },
      { id: "5.2.3-s1", text: "Know that isotopes of an element may be radioactive due to an excess of neutrons in the nucleus and/or the nucleus being too heavy", type: "supplement" },
      { id: "5.2.3-s2", text: "Describe the effect of alpha-decay, beta-decay and gamma-emissions on the nucleus, including an increase in stability and a reduction in the number of excess neutrons; the following change in the nucleus occurs during beta-emission: neutron -> proton + electron", type: "supplement" },
      { id: "5.2.3-s3", text: "Use decay equations, using nuclide notation, to show the emission of alpha-particles, beta-particles and gamma-radiation", type: "supplement" },
    ] },
    { id: "5.2.4", title: "Half-life", objectives: [
      { id: "5.2.4-c1", text: "Define the half-life of a particular isotope as the time taken for half the nuclei of that isotope in any sample to decay; recall and use this definition in simple calculations, which might involve information in tables or decay curves (calculations will not include background radiation)", type: "core" },
      { id: "5.2.4-s1", text: "Calculate half-life from data or decay curves from which background radiation has not been subtracted", type: "supplement" },
      { id: "5.2.4-s2", text: "Explain how the type of radiation emitted and the half-life of an isotope determine which isotope is used for applications including: (a) household fire (smoke) alarms (b) irradiating food to kill bacteria (c) sterilisation of equipment using gamma rays (d) measuring and controlling thicknesses of materials with the choice of radiations used linked to penetration and absorption (e) diagnosis and treatment of cancer using gamma rays", type: "supplement" },
    ] },
    { id: "5.2.5", title: "Safety precautions", objectives: [
      { id: "5.2.5-c1", text: "State the effects of ionising nuclear radiations on living things, including cell death, mutations and cancer", type: "core" },
      { id: "5.2.5-c2", text: "Describe how radioactive materials are moved, used and stored in a safe way", type: "core" },
      { id: "5.2.5-s1", text: "Explain safety precautions for all ionising radiation in terms of reducing exposure time, increasing distance between source and living tissue and using shielding to absorb radiation", type: "supplement" },
    ] },
  ] },
  { id: "6", title: "Space physics", groups: [
    { id: "6.1.1", title: "The Earth", objectives: [
      { id: "6.1.1-c1", text: "Know that the Earth is a planet that rotates on its axis, which is tilted, once in approximately 24 hours, and use this to explain observations of the apparent daily motion of the Sun and the periodic cycle of day and night", type: "core" },
      { id: "6.1.1-c2", text: "Know that the Earth orbits the Sun once in approximately 365 days and use this to explain the periodic nature of the seasons", type: "core" },
      { id: "6.1.1-c3", text: "Know that it takes approximately one month for the Moon to orbit the Earth and use this to explain the periodic nature of the Moon's cycle of phases", type: "core" },
      { id: "6.1.1-s1", text: "Define average orbital speed from the equation v = 2(pi)r/T where r is the average radius of the orbit and T is the orbital period; recall and use this equation", type: "supplement" },
    ] },
    { id: "6.1.2", title: "The Solar System", objectives: [
      { id: "6.1.2-c1", text: "Describe the Solar System as containing: (a) one star, the Sun (b) the eight named planets and know their order from the Sun (c) minor planets that orbit the Sun, including dwarf planets such as Pluto and asteroids in the asteroid belt (d) moons, that orbit the planets (e) smaller Solar System bodies, including comets and natural satellites", type: "core" },
      { id: "6.1.2-c2", text: "Know that, in comparison to each other, the four planets nearest the Sun are rocky and small and the four planets furthest from the Sun are gaseous and large, and explain this difference by referring to an accretion model for Solar System formation, to include: (a) the model's dependence on gravity (b) the presence of many elements in interstellar clouds of gas and dust (c) the rotation of material in the cloud and the formation of an accretion disc", type: "core" },
      { id: "6.1.2-c3", text: "Know that the strength of the gravitational field: (a) at the surface of a planet depends on the mass of the planet (b) around a planet decreases as the distance from the planet increases", type: "core" },
      { id: "6.1.2-c4", text: "Calculate the time it takes light to travel a significant distance such as between objects in the Solar System", type: "core" },
      { id: "6.1.2-c5", text: "Know that the Sun contains most of the mass of the Solar System and this explains why the planets orbit the Sun", type: "core" },
      { id: "6.1.2-c6", text: "Know that the force that keeps an object in orbit around the Sun is the gravitational attraction of the Sun", type: "core" },
      { id: "6.1.2-s1", text: "Know that planets, minor planets and comets have elliptical orbits, and recall that the Sun is not at the centre of the elliptical orbit, except when the orbit is approximately circular", type: "supplement" },
      { id: "6.1.2-s2", text: "Analyse and interpret planetary data about orbital distance, orbital duration, density, surface temperature and uniform gravitational field strength at the planet's surface", type: "supplement" },
      { id: "6.1.2-s3", text: "Know that the strength of the Sun's gravitational field decreases and that the orbital speeds of the planets decrease as the distance from the Sun increases", type: "supplement" },
      { id: "6.1.2-s4", text: "Know that an object in an elliptical orbit travels faster when closer to the Sun and explain this using the conservation of energy", type: "supplement" },
    ] },
    { id: "6.2.1", title: "The Sun as a star", objectives: [
      { id: "6.2.1-c1", text: "Know that the Sun is a star of medium size, consisting mostly of hydrogen and helium, and that it radiates most of its energy in the infrared, visible light and ultraviolet regions of the electromagnetic spectrum", type: "core" },
      { id: "6.2.1-s1", text: "Know that stars are powered by nuclear reactions that release energy and that in stable stars the nuclear reactions involve the fusion of hydrogen into helium", type: "supplement" },
    ] },
    { id: "6.2.2", title: "Stars", objectives: [
      { id: "6.2.2-c1", text: "State that: (a) galaxies are each made up of many billions of stars (b) the Sun is a star in the galaxy known as the Milky Way (c) other stars that make up the Milky Way are much further away from the Earth than the Sun is from the Earth (d) astronomical distances can be measured in light-years, where one light-year is the distance travelled in (the vacuum of) space by light in one year", type: "core" },
      { id: "6.2.2-s1", text: "Know that one light-year is equal to 9.5 x 10^15 m", type: "supplement" },
      { id: "6.2.2-s2", text: "Describe the life cycle of a star: (a) a star is formed from interstellar clouds of gas and dust that contain hydrogen (b) a protostar is an interstellar cloud collapsing and increasing in temperature as a result of its internal gravitational attraction (c) a protostar becomes a stable star when the inward force of gravitational attraction is balanced by an outward force due to the high temperature in the centre of the star (d) all stars eventually run out of hydrogen as fuel for the nuclear reaction (e) most stars expand to form red giants and more massive stars expand to form red supergiants when most of the hydrogen in the centre of the star has been converted to helium (f) a red giant from a less massive star forms a planetary nebula with a white dwarf star at its centre (g) a red supergiant explodes as a supernova, forming a nebula containing hydrogen and new heavier elements, leaving behind a neutron star or a black hole at its centre (h) the nebula from a supernova may form new stars with orbiting planets", type: "supplement" },
    ] },
    { id: "6.2.3", title: "The Universe", objectives: [
      { id: "6.2.3-c1", text: "Know that the Milky Way is one of many billions of galaxies making up the Universe and that the diameter of the Milky Way is approximately 100000 light-years", type: "core" },
      { id: "6.2.3-c2", text: "Describe redshift as an increase in the observed wavelength of electromagnetic radiation emitted from receding stars and galaxies", type: "core" },
      { id: "6.2.3-c3", text: "Know that the light emitted from distant galaxies appears redshifted in comparison with light emitted on the Earth", type: "core" },
      { id: "6.2.3-c4", text: "Know that redshift in the light from distant galaxies is evidence that the Universe is expanding and supports the Big Bang Theory", type: "core" },
      { id: "6.2.3-s1", text: "Know that microwave radiation of a specific frequency is observed at all points in space around us and is known as cosmic microwave background radiation (CMBR)", type: "supplement" },
      { id: "6.2.3-s2", text: "Explain that the CMBR was produced shortly after the Universe was formed and that this radiation has been expanded into the microwave region of the electromagnetic spectrum as the Universe expanded", type: "supplement" },
      { id: "6.2.3-s3", text: "Know that the speed v at which a galaxy is moving away from the Earth can be found from the change in wavelength of the galaxy's starlight due to redshift", type: "supplement" },
      { id: "6.2.3-s4", text: "Know that the distance d of a far galaxy can be determined using the brightness of a supernova in that galaxy", type: "supplement" },
      { id: "6.2.3-s5", text: "Define the Hubble constant H0 as the ratio of the speed at which the galaxy is moving away from the Earth to its distance from the Earth; recall and use the equation H0 = v/d", type: "supplement" },
      { id: "6.2.3-s6", text: "Know that the current estimate for H0 is 2.2 x 10^-18 per second", type: "supplement" },
      { id: "6.2.3-s7", text: "Know that the equation d/v = 1/H0 represents an estimate for the age of the Universe and that this is evidence for the idea that all the matter in the Universe was present at a single point", type: "supplement" },
    ] },
  ] },
];