#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Run from the app directory, since .vercel/project.json lives there.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

# Non-secret record. Named .env.* so the repo's .gitignore covers it, but not a
# name Next.js auto-loads. No credential is ever written here.
ENV_FILE=".env.rotation-record"

PROD_HOST="studytrack-cambridge-planner.vercel.app"

push_env() {
  local key="$1" value="$2" target="$3"
  vercel env rm "$key" "$target" --yes >/dev/null 2>&1 || true
  if printf '%s' "$value" | vercel env add "$key" "$target" >/dev/null 2>&1; then
    printf '  %s✓ set%s %s on %s\n' "$GREEN" "$RESET" "$key" "$target"
  else
    warn "could not set $key on $target"
    SKIPPED+=("Vercel env $key ($target) — set it by hand in the dashboard")
  fi
}

banner "Clerk: close public sign-up and move to production"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "What this changes"
say "Two separate problems, in order of how quickly they can be fixed:"
printf '\n'
step "Public sign-up is open. Anyone who finds the URL can create an account."
note "  Closed in stage 2. Takes about a minute and needs no deploy."
step "Clerk is on a DEVELOPMENT instance (sk_test_/pk_test_)."
note "  Fixed in stages 5-8. Needs DNS records, so allow real time for it."
printf '\n'
say "Closing sign-up costs this app nothing: it imports Clerk's SignIn component"
say "but has no SignUp component and no sign-up route, so it never offers"
say "registration itself. Teachers create students through the admin API, which"
say "keeps working -- invite-only blocks self-service sign-up, not admin"
say "creation."
printf '\n'
warn "You can stop after stage 3. Stage 4 asks."
printf '\n'

if ! command -v vercel >/dev/null 2>&1; then
  warn "The Vercel CLI is not on this shell's PATH."
  note "Try a PowerShell terminal, or install it here with:  npm i -g vercel"
  exit 1
fi
vercel whoami >/dev/null 2>&1 || { warn "Not logged in. Run 'vercel login', then re-run this."; exit 1; }
say "Vercel CLI ready, logged in as: $(vercel whoami 2>/dev/null | tail -n1)"
pause "Press Enter to begin."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Close public sign-up"
open_url "https://dashboard.clerk.com/last-active?path=user-authentication/restrictions"
say "In the Clerk dashboard, on the instance selector at the top left, make sure"
say "you are on the DEVELOPMENT instance -- that is the one serving your app now."
printf '\n'
step "Find the 'Access mode' setting (under Configure, with the restrictions)."
step "Change it from 'Public' to 'Invite-only'."
step "Save."
printf '\n'
note "Clerk calls this 'restricted' in its API. Users can then only arrive by"
note "invitation, enterprise connection, or being created by an admin -- which"
note "is exactly how your teacher creates students."
printf '\n'
warn "If you cannot find 'Access mode', the sidebar grouping has moved since"
warn "these docs. Search the dashboard for 'Restrictions' or 'Access mode'."
printf '\n'
confirm "Have you set the access mode to invite-only?" \
  && write_env CLERK_SIGNUP_CLOSED "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  || SKIPPED+=("close public sign-up on the development instance")

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Confirm sign-up is actually closed"
say "Settings pages can save without taking effect, so check it from outside."
printf '\n'
step "Open the app in a private/incognito window."
step "On the sign-in box, look for a 'Sign up' link."
step "It should be gone, or refuse to create an account if followed."
printf '\n'
open_url "https://$PROD_HOST"
note "An existing student signing in is unaffected; only new self-registration"
note "is blocked."
pause "Press Enter once you have checked."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Continue to the production instance?"
say "The immediate risk is now closed. What follows is a bigger job:"
step "Creating a production instance (new sk_live_/pk_live_ keys)."
step "Adding DNS records for Clerk's domains, then waiting for SSL."
step "Re-creating any OAuth credentials -- production cannot use Clerk's"
step "shared development OAuth credentials."
printf '\n'
warn "Your teacher and student accounts do NOT carry over. A production"
warn "instance starts with an empty user list, so every account has to be"
warn "recreated after the switch."
printf '\n'
note "That is the real cost here, and it is why doing this before real"
note "classroom use matters far more than doing it after."
printf '\n'

if ! confirm "Carry on to the production migration now?"; then
  say "Stopping here. Public sign-up is closed, which was the urgent part."
  SKIPPED+=("Clerk production instance -- re-run this wizard when you have time for DNS")
  finish
  exit 0
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create the production instance"
open_url "https://dashboard.clerk.com"
step "Select 'Development' in the instance picker at the top."
step "Choose 'Create production instance' from the dropdown."
step "Decide whether to clone your development settings or start from defaults."
note "Cloning carries your settings across, but never your users."
printf '\n'
say "The production instance homepage then lists what is still outstanding --"
say "usually DNS records and the SSL certificate."
printf '\n'
pause "Press Enter once the production instance exists."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Complete the deployment requirements"
say "Work through Clerk's checklist on the production instance homepage:"
step "Add the DNS records it lists, at your domain registrar."
step "Wait for Clerk to verify them; SSL is issued after that."
step "Recreate OAuth credentials if you use any social sign-in."
printf '\n'
warn "DNS propagation is not instant. This stage can legitimately take hours."
note "You can Ctrl-C here and re-run the wizard later; nothing is half-applied."
printf '\n'
warn "Expect at least one plan-gated feature to block the checklist."
say "Every feature is free on a development instance, so cloning those settings"
say "carries options across that production will not accept. The usual one is:"
note "  \"The SMS code (MFA) feature is not available on your current plan\""
printf '\n'
step "Open Configure -> Multi-factor on the PRODUCTION instance."
step "Turn off SMS verification code."
printf '\n'
note "Nothing in StudyTrack uses it. Accounts are username and password only --"
note "no phone number, no email, no second factor -- so turning it off costs"
note "nothing. The same applies to any other paid feature the clone dragged in:"
note "turn it off rather than paying for something the app never calls."
printf '\n'
open_url "https://dashboard.clerk.com"
pause "Press Enter once Clerk reports the instance is ready."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Publish the live keys"
open_url "https://dashboard.clerk.com/last-active?path=api-keys"
say "With the PRODUCTION instance selected in the picker, open 'API keys'."
printf '\n'

while true; do
  ask LIVE_PUBLISHABLE_KEY "Paste the publishable key (pk_live_...):"
  [[ "$LIVE_PUBLISHABLE_KEY" == pk_live_* ]] && break
  warn "That should start with pk_live_. If it starts with pk_test_ you are"
  warn "still on the development instance -- switch the picker at the top left."
done

while true; do
  ask_secret LIVE_SECRET_KEY "Paste the secret key (sk_live_...):"
  [[ "$LIVE_SECRET_KEY" == sk_live_* ]] && break
  warn "That should start with sk_live_. Check the instance picker."
done

printf '\n'
say "Publishing to Vercel production only -- preview and development keep the"
say "test keys, so you can still develop against the dev instance."
push_env NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY "$LIVE_PUBLISHABLE_KEY" production
push_env CLERK_SECRET_KEY "$LIVE_SECRET_KEY" production

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Redeploy, verify, and close sign-up on production"
say "Finding the current production deployment..."
DEPLOYMENT=$(vercel ls --yes 2>/dev/null | awk '
  match($0, /https:\/\/[a-z0-9.-]+\.vercel\.app/) {
    url = substr($0, RSTART, RLENGTH)
  }
  /Production/ && url { print url; exit }
' || true)

if [[ -n "$DEPLOYMENT" ]]; then
  say "Found: $DEPLOYMENT"
else
  warn "Could not detect it automatically."
  note "Copy the deployment's own *.vercel.app address, NOT a vercel.com/... link."
  open_url "https://vercel.com/dashboard"
  for _ in 1 2 3 4 5; do
    ask DEPLOYMENT "Paste the production deployment URL:"
    [[ "$DEPLOYMENT" == *"vercel.com/"* ]] && { warn "That is the dashboard URL."; continue; }
    [[ "$DEPLOYMENT" == *".vercel.app"* ]] && break
    warn "That does not look like a *.vercel.app deployment URL."
  done
fi

if [[ "$DEPLOYMENT" == *".vercel.app"* ]]; then
  vercel redeploy "$DEPLOYMENT" --target=production || {
    warn "CLI redeploy failed -- redeploy from the dashboard instead."
    SKIPPED+=("production redeploy")
  }
else
  SKIPPED+=("production redeploy -- do it from the Vercel dashboard")
fi
pause "Wait for the deployment to go green, then press Enter."

code=$(curl -s -o /dev/null -w '%{http_code}' "https://$PROD_HOST" || echo "000")
[[ "$code" == "200" ]] && say "Site responds 200." || warn "Site returned HTTP $code -- check the deployment logs."
printf '\n'
warn "The user list is empty on a fresh production instance."
step "Sign up or create the teacher account again."
step "Visit /api/setup/claim-teacher, or use the in-app prompt, to claim the"
step "teacher role -- it works because the instance has no teacher yet."
step "Then recreate the student accounts."
printf '\n'
note "Do that BEFORE closing sign-up below, or you will lock yourself out of"
note "creating the first account."
open_url "https://$PROD_HOST"
pause "Press Enter once the teacher account exists again."

printf '\n'
open_url "https://dashboard.clerk.com/last-active?path=user-authentication/restrictions"
say "Finally, close sign-up on the production instance too:"
step "With PRODUCTION selected, set 'Access mode' to 'Invite-only'."
printf '\n'
if confirm "Have you closed sign-up on production?"; then
  write_env CLERK_PRODUCTION_COMPLETED "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
else
  SKIPPED+=("close public sign-up on the PRODUCTION instance -- it is open right now")
fi

finish
