#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Run from the app directory, since .vercel/project.json lives there.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

# Non-secret record. Named .env.* so the repo's .gitignore covers it, but not a
# name Next.js auto-loads. No credential is ever written here.
ENV_FILE=".env.rotation-record"

PROD_HOST="studytrack-cambridge-planner.vercel.app"

# push_env KEY VALUE TARGET replaces an environment variable on Vercel.
# printf (not echo) because a trailing newline would become part of the value.
push_env() {
  local key="$1" value="$2" target="$3"
  vercel env rm "$key" "$target" --yes >/dev/null 2>&1 || true
  if printf '%s' "$value" | vercel env add "$key" "$target" >/dev/null 2>&1; then
    printf '  %s✓ set%s %s on %s\n' "$GREEN" "$RESET" "$key" "$target"
  else
    warn "could not set $key on $target"
    SKIPPED+=("Vercel env $key ($target) — set it by hand in the dashboard")
  fi
}

banner "Clerk: rotate the exposed secret key"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Pre-flight"
say "CLERK_SECRET_KEY was printed into a Claude Code transcript, so it must be"
say "treated as public. Only the SECRET key is affected."
note "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY is published to every browser by design."
note "It does not need rotating and is not touched here."
printf '\n'
say "Clerk allows several secret keys at once, so this rotation has no downtime:"
step "Add a new key, deploy it, verify it, and only then delete the old one."
printf '\n'
warn "If you are moving to a Clerk PRODUCTION instance today, stop and run"
warn "harden-clerk.sh instead -- it issues fresh sk_live_ keys and makes this"
warn "rotation redundant. Run this one if production is days away."
printf '\n'

if ! command -v vercel >/dev/null 2>&1; then
  warn "The Vercel CLI is not on this shell's PATH."
  note "It is installed, but Git Bash may not see it. Try a PowerShell terminal,"
  note "or install it here with:  npm i -g vercel"
  exit 1
fi
say "Vercel CLI found: $(vercel --version 2>/dev/null | head -n1)"

if ! vercel whoami >/dev/null 2>&1; then
  warn "Not logged in. Run 'vercel login' in another terminal, then re-run this."
  exit 1
fi
say "Logged in as: $(vercel whoami 2>/dev/null | tail -n1)"

if [[ ! -f .vercel/project.json ]]; then
  warn "No .vercel/project.json in $REPO_DIR -- run 'vercel link' first."
  exit 1
fi
say "Project linked: $(node -p "require('./.vercel/project.json').projectName" 2>/dev/null || echo 'studytrack-cambridge-planner')"

write_env CLERK_ROTATION_STARTED "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
confirm "Ready to start?" || { say "Nothing changed. Re-run when ready."; exit 0; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Clerk: create a new secret key"
open_url "https://dashboard.clerk.com/last-active?path=api-keys"
say "In the Clerk dashboard:"
step "Check the instance selector at the top left says 'Development'."
step "Open 'API keys' in the sidebar."
step "Under 'Secret keys', choose '+ Add new key'."
step "Name it something datestamped, e.g. rotated-$(date -u +%Y-%m-%d)."
step "Create it, then copy the new key."
printf '\n'
note "Do NOT delete the old key yet. Deleting it before the new one is deployed"
note "would break every signed-in session immediately. Stage 6 deletes it."
printf '\n'

# The secret key and the publishable key must belong to the SAME Clerk
# instance. An sk_live_ key paired with a pk_test_ frontend authenticates
# nobody: the browser holds a session issued by one instance and the server
# validates it against another, so every request arrives looking signed out.
# Nothing in the resulting 401s says "wrong instance", which makes this
# expensive to diagnose -- hence checking it here, before it is deployed.
EXPECTED_KIND=""
PUBLISHABLE_KIND=""
if [[ -f .env.local ]]; then
  PK_LINE=$(grep -E '^NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=' .env.local | head -n1 || true)
  PK_VALUE=$(printf '%s' "$PK_LINE" | sed -E 's/^[^=]+=//; s/^"//; s/"$//')
  case "$PK_VALUE" in
    pk_test_*) EXPECTED_KIND="sk_test_"; PUBLISHABLE_KIND="pk_test_" ;;
    pk_live_*) EXPECTED_KIND="sk_live_"; PUBLISHABLE_KIND="pk_live_" ;;
  esac
fi

if [[ -n "$EXPECTED_KIND" ]]; then
  say "This app ships a ${PUBLISHABLE_KIND} publishable key, so the secret key"
  say "must start ${EXPECTED_KIND} -- the same instance."
else
  warn "Could not read the publishable key from .env.local, so the instance"
  warn "cannot be checked here. Make sure the dashboard's instance selector"
  warn "matches the instance this app actually uses."
fi
printf '\n'

while true; do
  ask_secret NEW_CLERK_SECRET_KEY "Paste the new secret key:"
  if [[ -z "$NEW_CLERK_SECRET_KEY" ]]; then
    warn "Empty -- paste the key, or Ctrl-C to abort."
  elif [[ "$NEW_CLERK_SECRET_KEY" != sk_* ]]; then
    warn "A Clerk secret key starts with sk_test_ or sk_live_."
    note "If what you copied starts with pk_, that is the publishable key."
  elif [[ -n "$EXPECTED_KIND" && "$NEW_CLERK_SECRET_KEY" != ${EXPECTED_KIND}* ]]; then
    warn "That key belongs to a different instance than this app's frontend."
    say "Expected a key starting ${EXPECTED_KIND}, to match the ${PUBLISHABLE_KIND}"
    say "publishable key the app ships."
    printf '\n'
    step "Switch the instance selector at the TOP LEFT of the Clerk dashboard."
    step "Open API keys again there, and copy the secret key from that instance."
    printf '\n'
    note "Deploying this key would sign every user out and make each request"
    note "look unauthenticated, with no error that points at the cause."
  else
    break
  fi
done
say "New secret key captured, matching the app's instance."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Vercel: publish the new key"
say "Setting CLERK_SECRET_KEY on all three targets..."
push_env CLERK_SECRET_KEY "$NEW_CLERK_SECRET_KEY" production
push_env CLERK_SECRET_KEY "$NEW_CLERK_SECRET_KEY" preview
push_env CLERK_SECRET_KEY "$NEW_CLERK_SECRET_KEY" development
printf '\n'
note "Environment changes only reach running functions on a new deployment,"
note "so the old key stays in use until stage 4 finishes."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Redeploy production"
say "Finding the current production deployment..."
# `vercel ls` wraps a row across two lines at narrow widths, so the URL and the
# "Production" label are not reliably on the same line. Remember the last URL
# seen and emit it when the Production marker turns up.
DEPLOYMENT=$(vercel ls --yes 2>/dev/null | awk '
  match($0, /https:\/\/[a-z0-9.-]+\.vercel\.app/) {
    url = substr($0, RSTART, RLENGTH)
  }
  /Production/ && url { print url; exit }
' || true)

if [[ -n "$DEPLOYMENT" ]]; then
  say "Found: $DEPLOYMENT"
else
  warn "Could not detect it automatically."
  step "Open the project's Deployments tab and copy the latest Production URL."
  note "It must be the deployment's own *.vercel.app address, NOT the"
  note "vercel.com/... dashboard link -- redeploy cannot use a dashboard URL."
  open_url "https://vercel.com/dashboard"
  for _ in 1 2 3 4 5; do
    ask DEPLOYMENT "Paste the production deployment URL:"
    [[ "$DEPLOYMENT" == *"vercel.com/"* ]] && { warn "That is the dashboard URL. Open the deployment itself."; continue; }
    [[ "$DEPLOYMENT" == *".vercel.app"* ]] && break
    warn "That does not look like a *.vercel.app deployment URL."
  done
fi

if [[ "$DEPLOYMENT" == *".vercel.app"* ]]; then
  if vercel redeploy "$DEPLOYMENT" --target=production; then
    say "Redeploy triggered."
  else
    warn "CLI redeploy failed -- trigger it from the dashboard instead."
    step "Deployments -> the latest production one -> ... -> Redeploy."
  fi
else
  warn "No usable deployment URL; redeploy from the dashboard."
  SKIPPED+=("production redeploy -- do it from the Vercel dashboard")
fi
pause "Wait for the deployment to go green, then press Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify the new key works"
say "Checking https://$PROD_HOST ..."
code=$(curl -s -o /dev/null -w '%{http_code}' "https://$PROD_HOST" || echo "000")
if [[ "$code" == "200" ]]; then
  say "Site responds 200."
else
  warn "Site returned HTTP $code -- check the deployment logs before continuing."
fi
printf '\n'
say "A 200 only proves the build shipped. The new key is exercised by anything"
say "that calls Clerk's Backend API, so prove it properly:"
step "Sign in as the teacher."
step "Open the students list (calls clerkClient to list users)."
printf '\n'
warn "Do not continue to stage 6 until that worked. Deleting the old key while"
warn "the app still depends on it would break sign-in for everyone."
open_url "https://$PROD_HOST"
pause "Press Enter once you have confirmed the students list loads."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Clerk: delete the exposed key"
open_url "https://dashboard.clerk.com/last-active?path=api-keys"
say "This is the step that actually ends the exposure."
step "Under 'Secret keys', find the OLD key -- not the one you just made."
step "Check its 'Last used' timestamp: it should have stopped being used"
step "when the redeploy went live."
step "Delete it and confirm."
printf '\n'
note "Clerk warns you if a key was used recently. If it warns about the old key,"
note "the redeploy has not taken effect yet -- go back and check stage 5."
printf '\n'

if confirm "Have you deleted the old key?"; then
  write_env CLERK_ROTATION_COMPLETED "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  say "The exposed key is now dead."
else
  warn "The exposed key is still valid. Nothing is fixed until it is deleted."
  SKIPPED+=("delete the old Clerk secret key -- the exposed key is still live")
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Refresh local environment"
say "Your local .env.local still holds the old key."
if confirm "Pull the new values into .env.local now?"; then
  if vercel env pull .env.local --yes >/dev/null 2>&1; then
    say "Pulled fresh values into .env.local"
  else
    warn "Pull failed -- run it yourself:  vercel env pull .env.local"
    SKIPPED+=("local .env.local refresh -- run: vercel env pull .env.local")
  fi
fi
printf '\n'
say "Still worth doing separately:"
step "Move to a Clerk production instance and close public sign-up."
step "Run scripts/harden-clerk.sh for both."

finish
