#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=8

# Run from the app directory, since .vercel/project.json lives there.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

# Non-secret rotation record. Named .env.* so the repo's .gitignore covers it,
# but not a name Next.js auto-loads. No credential is ever written here.
ENV_FILE=".env.rotation-record"

NEON_PROJECT="raspy-rice-40549761"
NEON_ROLE="neondb_owner"
PROD_HOST="studytrack-cambridge-planner.vercel.app"

# push_env KEY VALUE TARGET replaces an environment variable on Vercel.
# printf (not echo) because a trailing newline would become part of the value.
push_env() {
  local key="$1" value="$2" target="$3"
  vercel env rm "$key" "$target" --yes >/dev/null 2>&1 || true
  if printf '%s' "$value" | vercel env add "$key" "$target" >/dev/null 2>&1; then
    printf '  %s✓ set%s %s on %s\n' "$GREEN" "$RESET" "$key" "$target"
  else
    warn "could not set $key on $target"
    SKIPPED+=("Vercel env $key ($target) — set it by hand in the dashboard")
  fi
}

banner "StudyTrack: rotate leaked database and blob credentials"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Pre-flight"
say "Rotating invalidates the old credentials immediately, so production will"
say "be down until stage 6 redeploys. A few minutes, typically."
warn "Do not run this while a student is part-way through a paper."
note "Their drafts are safe (IndexedDB + server), but a submit in the window fails."
printf '\n'

if ! command -v vercel >/dev/null 2>&1; then
  warn "The Vercel CLI is not on this shell's PATH."
  note "On Windows it is often installed but visible only to PowerShell, not to"
  note "Git Bash. Launch this wizard from PowerShell so it inherits that PATH:"
  note ""
  note "  & \"C:\\Program Files\\Git\\bin\\bash.exe\" scripts/rotate-credentials.sh"
  note ""
  note "If it genuinely is not installed:  npm i -g vercel"
  exit 1
fi
say "Vercel CLI found: $(vercel --version 2>/dev/null | head -n1)"

if ! vercel whoami >/dev/null 2>&1; then
  warn "Not logged in. Run 'vercel login' in another terminal, then re-run this."
  exit 1
fi
say "Logged in as: $(vercel whoami 2>/dev/null | tail -n1)"

if [[ ! -f .vercel/project.json ]]; then
  warn "No .vercel/project.json in $REPO_DIR — run 'vercel link' first."
  exit 1
fi
say "Project linked: $(node -p "require('./.vercel/project.json').projectName" 2>/dev/null || echo 'studytrack-cambridge-planner')"

printf '\n'
# Ask the CLI rather than the human: the dashboard URL people naturally copy
# (vercel.com/<team>/<project>/<id>) is not what `vercel redeploy` accepts, and
# it fails with a confusing "Can't find the deployment vercel.com".
say "Finding the current production deployment..."
# `vercel ls` wraps a row across two lines at narrow widths, so the URL and the
# "Production" label are not reliably on the same line. Remember the last URL
# seen and emit it when the Production marker turns up.
ROLLBACK_DEPLOYMENT=$(vercel ls --yes 2>/dev/null | awk '
  match($0, /https:\/\/[a-z0-9.-]+\.vercel\.app/) {
    url = substr($0, RSTART, RLENGTH)
  }
  /Production/ && url { print url; exit }
' || true)

if [[ -n "$ROLLBACK_DEPLOYMENT" ]]; then
  say "Found: $ROLLBACK_DEPLOYMENT"
else
  warn "Could not detect it automatically."
  step "Run 'vercel ls' and copy the URL on the row marked Production."
  note "It looks like https://<project>-<hash>-<team>.vercel.app"
  note "NOT the dashboard link (https://vercel.com/...), which redeploy rejects."
  while true; do
    ask ROLLBACK_DEPLOYMENT "Paste the production deployment URL (or Enter to skip):"
    [[ -z "$ROLLBACK_DEPLOYMENT" ]] && break
    if [[ "$ROLLBACK_DEPLOYMENT" == *"vercel.com/"* ]]; then
      warn "That is the dashboard URL. Redeploy needs the *.vercel.app one."
    elif [[ "$ROLLBACK_DEPLOYMENT" != *".vercel.app"* ]]; then
      warn "Expected a *.vercel.app deployment URL."
    else
      break
    fi
  done
fi
[[ -n "$ROLLBACK_DEPLOYMENT" ]] && write_env ROLLBACK_DEPLOYMENT "$ROLLBACK_DEPLOYMENT"
write_env ROTATION_STARTED "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

confirm "Ready to invalidate the current credentials?" || { say "Nothing changed. Re-run when ready."; exit 0; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Neon: reset the database password"
open_url "https://console.neon.tech/app/projects/$NEON_PROJECT"
say "In the Neon console for project $NEON_PROJECT:"
step "Sidebar → Branches → click the branch that owns the role."
step "Open the 'Roles & Databases' tab."
step "On the '$NEON_ROLE' row, open its menu → Reset password → Reset."
step "Then open the Connect modal and set connection type to 'Pooled connection'."
printf '\n'
warn "Copy the POOLED string — its host must contain '-pooler'."
note "The modal often defaults to the direct endpoint. The direct one will appear"
note "to work, then fail under load with connection exhaustion."
note "If you use more than one Neon branch, reset the role on each; resets are"
note "branch-scoped."
printf '\n'

attempts=0
while (( attempts < 5 )); do
  attempts=$((attempts + 1))
  ask_secret NEW_DATABASE_URL "Paste the new POOLED connection string:"
  if [[ -z "$NEW_DATABASE_URL" ]]; then
    warn "Empty — paste the string, or Ctrl-C to abort."
  elif [[ "$NEW_DATABASE_URL" != *"-pooler."* ]]; then
    warn "That host has no '-pooler' in it, so it is the direct endpoint."
    say "Switch the Connect modal to 'Pooled connection' and copy again."
  elif [[ "$NEW_DATABASE_URL" != postgres* ]]; then
    warn "That does not start with postgres:// or postgresql://."
  else
    break
  fi
done
if [[ -z "${NEW_DATABASE_URL:-}" || "$NEW_DATABASE_URL" != *"-pooler."* ]]; then
  warn "No valid pooled connection string after $attempts attempts. Aborting."
  note "Nothing was pushed to Vercel. The Neon password IS already reset, so"
  note "update DATABASE_URL by hand before the app can reconnect."
  exit 1
fi
say "Pooled connection string captured."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Vercel: update DATABASE_URL"
say "The Neon integration may have already synced this for you."
open_url "https://vercel.com/dashboard"
step "Open the project → Settings → Environment Variables."
step "Look at DATABASE_URL and compare it with what you just copied."
printf '\n'

if confirm "Has DATABASE_URL already updated itself?"; then
  say "Good — the integration synced it. Leaving it alone."
else
  say "Setting it on all three targets..."
  push_env DATABASE_URL "$NEW_DATABASE_URL" production
  push_env DATABASE_URL "$NEW_DATABASE_URL" preview
  push_env DATABASE_URL "$NEW_DATABASE_URL" development
  printf '\n'
  note "If it reverts later, force a resync: Neon Console → Integrations →"
  note "Manage → Settings → Save changes."
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Vercel Blob: rotate the read-write token"
say "BLOB_READ_WRITE_TOKEN grants read/write on every uploaded paper and every"
say "handwritten student answer. It was in the leaked file too."
printf '\n'
open_url "https://vercel.com/dashboard/stores"
step "Open your Blob store → its settings / tokens section."
step "Create a new read-write token if offered, otherwise regenerate the existing one."
printf '\n'
warn "I could not confirm this screen's exact layout from Vercel's docs."
note "If your store only exposes one managed token, regenerating it is correct."
note "If you can create a second token first, do that — it avoids extra downtime."
printf '\n'

if confirm "Did you get a new blob token to paste?"; then
  ask_secret NEW_BLOB_TOKEN "Paste the new BLOB_READ_WRITE_TOKEN:"
  if [[ -n "$NEW_BLOB_TOKEN" ]]; then
    push_env BLOB_READ_WRITE_TOKEN "$NEW_BLOB_TOKEN" production
    push_env BLOB_READ_WRITE_TOKEN "$NEW_BLOB_TOKEN" preview
    push_env BLOB_READ_WRITE_TOKEN "$NEW_BLOB_TOKEN" development
  else
    SKIPPED+=("BLOB_READ_WRITE_TOKEN — nothing pasted; the leaked token is still live")
  fi
else
  warn "Skipping the blob token. The leaked one stays valid until you rotate it."
  SKIPPED+=("BLOB_READ_WRITE_TOKEN — still the leaked value; rotate it separately")
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Clean up the stale Postgres variables"
say "The Neon integration also sets 12 variables your code never reads:"
note "PGHOST PGUSER PGPASSWORD PGDATABASE POSTGRES_URL POSTGRES_USER"
note "POSTGRES_HOST POSTGRES_PASSWORD POSTGRES_DATABASE POSTGRES_PRISMA_URL"
note "POSTGRES_URL_NON_POOLING POSTGRES_URL_NO_SSL"
printf '\n'
say "Only DATABASE_URL is read (lib/db.ts). The rest now hold the dead password,"
say "so anyone reading them later gets credentials that silently do not work."
printf '\n'
warn "Leave them if the Neon integration manages them — it will resync them."
note "Remove them only if you are sure nothing else depends on them."

if confirm "Remove these stale variables from production?"; then
  for key in PGHOST PGUSER PGPASSWORD PGDATABASE POSTGRES_URL POSTGRES_USER \
             POSTGRES_HOST POSTGRES_PASSWORD POSTGRES_DATABASE POSTGRES_PRISMA_URL \
             POSTGRES_URL_NON_POOLING POSTGRES_URL_NO_SSL; do
    if vercel env rm "$key" production --yes >/dev/null 2>&1; then
      printf '  %s✓ removed%s %s\n' "$GREEN" "$RESET" "$key"
    fi
  done
else
  say "Left in place."
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Redeploy production"
warn "Until this finishes, the live app cannot reach the database."
say "Environment changes only reach running functions on a new deployment."
printf '\n'

if [[ -n "${ROLLBACK_DEPLOYMENT:-}" ]]; then
  say "Redeploying from: $ROLLBACK_DEPLOYMENT"
  if vercel redeploy "$ROLLBACK_DEPLOYMENT" --target=production; then
    say "Redeploy triggered."
  else
    warn "CLI redeploy failed — trigger it from the dashboard instead."
    step "Deployments → the latest production one → ⋯ → Redeploy."
    pause "Press Enter once the redeploy is building."
  fi
else
  open_url "https://vercel.com/dashboard"
  step "Deployments → latest production deployment → ⋯ → Redeploy."
  pause "Press Enter once the redeploy has finished."
fi
pause "Wait for the deployment to go green, then press Enter."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify the app reconnected"
say "Checking https://$PROD_HOST ..."
code=$(curl -s -o /dev/null -w '%{http_code}' "https://$PROD_HOST" || echo "000")
if [[ "$code" == "200" ]]; then
  say "Site responds 200."
else
  warn "Site returned HTTP $code — check the deployment logs before continuing."
fi
printf '\n'
say "The page loading only proves the build shipped. To prove the new"
say "credentials actually work, exercise the database and blob storage:"
step "Sign in as a teacher."
step "Open a paper (reads the database and fetches the PDF from blob storage)."
step "If both render, the rotation worked."
printf '\n'
open_url "https://$PROD_HOST"
pause "Press Enter once you have checked."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Refresh local environment"
say "Your local .env.local still holds the dead credentials."
if confirm "Pull the new values into .env.local now?"; then
  if vercel env pull .env.local --yes >/dev/null 2>&1; then
    say "Pulled fresh values into .env.local"
  else
    warn "Pull failed — run it yourself:  vercel env pull .env.local"
    SKIPPED+=("local .env.local refresh — run: vercel env pull .env.local")
  fi
fi
write_env ROTATION_COMPLETED "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
printf '\n'
say "Finally, the point of all this:"
step "The old database password and blob token are now dead."
step "Anyone holding a copy of the old zip can no longer reach student data."

finish
