// The Stage 8 and Stage 9 learning objectives of the Cambridge Lower Secondary
// Mathematics curriculum framework (0862, published September 2020 for first
// teaching September 2021, version 2), and the practice unit each belongs to.
//
// Descriptions are StudyTrack's own short summaries, not Cambridge's wording.
// The codes are what matter: tests/lower-secondary/coverage.test.ts fails if
// any code here is not assessed by at least one question template in its unit.

export type Stage = 8 | 9;
export type Objective = { code: string; unit: string; summary: string };

export const framework: Objective[] = [
  // ---- Stage 8: Number ----------------------------------------------------
  { code: "8Ni.01", unit: "s8-u1", summary: "Order of operations with brackets, indices and square/cube roots" },
  { code: "8Ni.02", unit: "s8-u1", summary: "Estimate, multiply and divide integers; sign generalisations" },
  { code: "8Ni.03", unit: "s8-u1", summary: "Factors, multiples, prime factors, HCF and LCM" },
  { code: "8Ni.04", unit: "s8-u1", summary: "Natural numbers, integers and rational numbers as a hierarchy" },
  { code: "8Ni.05", unit: "s8-u1", summary: "Positive and zero indices; index laws for multiplication and division" },
  { code: "8Ni.06", unit: "s8-u1", summary: "Squares of positive and negative numbers and both square roots" },
  { code: "8Ni.07", unit: "s8-u1", summary: "Positive and negative cube numbers and cube roots" },
  { code: "8Np.01", unit: "s8-u3", summary: "Multiply and divide integers and decimals by 0.1 and 0.01" },
  { code: "8Np.02", unit: "s8-u3", summary: "Round to a given number of significant figures" },
  { code: "8Nf.01", unit: "s8-u7", summary: "Fractions equivalent to recurring decimals" },
  { code: "8Nf.02", unit: "s8-u7", summary: "Estimate and subtract mixed numbers; answer as a simplified mixed number" },
  { code: "8Nf.03", unit: "s8-u7", summary: "Integer times a mixed number; integer divided by a proper fraction" },
  { code: "8Nf.04", unit: "s8-u4", summary: "Laws of arithmetic and order of operations with decimals and fractions" },
  { code: "8Nf.05", unit: "s8-u10", summary: "Percentage increase and decrease, and absolute change" },
  { code: "8Nf.06", unit: "s8-u4", summary: "Compare and order positive and negative decimals and fractions with =, ≠, <, >, ≤, ≥" },
  { code: "8Nf.07", unit: "s8-u4", summary: "Estimate and multiply decimals by integers and decimals" },
  { code: "8Nf.08", unit: "s8-u4", summary: "Estimate and divide decimals by numbers with one decimal place" },
  { code: "8Nf.09", unit: "s8-u12", summary: "Ratio and direct proportion" },
  { code: "8Nf.10", unit: "s8-u12", summary: "Simplify and compare ratios, including different units" },
  { code: "8Nf.11", unit: "s8-u12", summary: "Divide an amount in a ratio with two or more parts" },
  // ---- Stage 8: Algebra ---------------------------------------------------
  { code: "8Ae.01", unit: "s8-u2", summary: "What letters mean in expressions, formulae and equations" },
  { code: "8Ae.02", unit: "s8-u2", summary: "Laws of arithmetic applied to algebraic terms, including squares and cubes" },
  { code: "8Ae.03", unit: "s8-u2", summary: "Expand a single bracket (squares and cubes) and factorise by the HCF" },
  { code: "8Ae.04", unit: "s8-u2", summary: "Words to linear expressions and back, including fractional coefficients" },
  { code: "8Ae.05", unit: "s8-u2", summary: "Words to formulae and back; change the subject (mixed operations)" },
  { code: "8Ae.06", unit: "s8-u2", summary: "Form and solve equations, including fractional coefficients and unknowns on both sides" },
  { code: "8Ae.07", unit: "s8-u2", summary: "Letters representing open and closed intervals" },
  { code: "8As.01", unit: "s8-u9", summary: "Term-to-term rules; sequences from numerical and spatial patterns, including fractions" },
  { code: "8As.02", unit: "s8-u9", summary: "nth term rules with positive, negative or fractional coefficients" },
  { code: "8As.03", unit: "s8-u9", summary: "Functions: outputs from inputs, and inputs from outputs by inverse operations" },
  { code: "8As.04", unit: "s8-u11", summary: "Words to a linear function y = mx + c and back" },
  { code: "8As.05", unit: "s8-u11", summary: "Tables of values and graphs of y = mx + c" },
  { code: "8As.06", unit: "s8-u11", summary: "Gradient and y-intercept of y = mx + c" },
  { code: "8As.07", unit: "s8-u11", summary: "Graphs with more than one part; meaning of intersections" },
  // ---- Stage 8: Geometry and measure --------------------------------------
  { code: "8Gg.01", unit: "s8-u8", summary: "Hierarchy of quadrilaterals" },
  { code: "8Gg.02", unit: "s8-u15", summary: "π as circumference ÷ diameter; circumference of a circle" },
  { code: "8Gg.03", unit: "s8-u15", summary: "Miles and kilometres (5 miles ≈ 8 km)" },
  { code: "8Gg.04", unit: "s8-u15", summary: "Area of parallelograms and trapezia" },
  { code: "8Gg.05", unit: "s8-u8", summary: "Euler's formula for vertices, faces and edges" },
  { code: "8Gg.06", unit: "s8-u15", summary: "Volume of a triangular prism" },
  { code: "8Gg.07", unit: "s8-u8", summary: "Front, side and top views of 3D shapes" },
  { code: "8Gg.08", unit: "s8-u15", summary: "Surface area of cubes, cuboids, triangular prisms and pyramids" },
  { code: "8Gg.09", unit: "s8-u8", summary: "Regular polygons: sides, lines of symmetry and order of rotation" },
  { code: "8Gg.10", unit: "s8-u5", summary: "Exterior angle of a triangle equals the two interior opposite angles" },
  { code: "8Gg.11", unit: "s8-u5", summary: "Alternate, corresponding and vertically opposite angles" },
  { code: "8Gg.12", unit: "s8-u5", summary: "Constructions: triangles, midpoints, perpendicular and angle bisectors" },
  { code: "8Gp.01", unit: "s8-u5", summary: "Bearings as a measure of direction" },
  { code: "8Gp.02", unit: "s8-u14", summary: "Midpoint of a line segment from coordinates" },
  { code: "8Gp.03", unit: "s8-u14", summary: "Translation by a vector; the image is congruent" },
  { code: "8Gp.04", unit: "s8-u14", summary: "Reflection in lines parallel to the axes and in y = ±x" },
  { code: "8Gp.05", unit: "s8-u14", summary: "Rotation: centre, direction and angle" },
  { code: "8Gp.06", unit: "s8-u14", summary: "Enlargement from a centre with a positive integer scale factor" },
  // ---- Stage 8: Statistics and probability ---------------------------------
  { code: "8Ss.01", unit: "s8-u6", summary: "Choose data to collect; categorical, discrete and continuous data" },
  { code: "8Ss.02", unit: "s8-u6", summary: "Advantages and disadvantages of sampling methods" },
  { code: "8Ss.03", unit: "s8-u6", summary: "Record and represent data; choose a suitable representation" },
  { code: "8Ss.04", unit: "s8-u16", summary: "Compare two distributions using averages and range" },
  { code: "8Ss.05", unit: "s8-u16", summary: "Interpret data and discuss conclusions, including variation" },
  { code: "8Sp.01", unit: "s8-u13", summary: "Complementary events" },
  { code: "8Sp.02", unit: "s8-u13", summary: "Lists, tables and diagrams of combined outcomes" },
  { code: "8Sp.03", unit: "s8-u13", summary: "Theoretical probability of equally likely combined events" },
  { code: "8Sp.04", unit: "s8-u13", summary: "Experiments: compare experimental with theoretical probability" },

  // ---- Stage 9: Number ----------------------------------------------------
  { code: "9Ni.01", unit: "s9-u1", summary: "Rational and irrational numbers" },
  { code: "9Ni.02", unit: "s9-u1", summary: "Positive, negative and zero indices; index laws" },
  { code: "9Ni.03", unit: "s9-u3", summary: "Standard form for large and small numbers" },
  { code: "9Ni.04", unit: "s9-u1", summary: "Estimate surds using square and cube roots" },
  { code: "9Np.01", unit: "s9-u3", summary: "Multiply and divide by 10 to any positive or negative power" },
  { code: "9Np.02", unit: "s9-u3", summary: "Upper and lower limits of a rounded number" },
  { code: "9Nf.01", unit: "s9-u8", summary: "Deduce whether a fraction's decimal terminates or recurs" },
  { code: "9Nf.02", unit: "s9-u8", summary: "Add and subtract proper and improper fractions and mixed numbers" },
  { code: "9Nf.03", unit: "s9-u8", summary: "Multiply and divide fractions, cancelling common factors" },
  { code: "9Nf.04", unit: "s9-u8", summary: "Simplify calculations with decimals and fractions using the laws of arithmetic" },
  { code: "9Nf.05", unit: "s9-u3", summary: "Compound percentages" },
  { code: "9Nf.06", unit: "s9-u3", summary: "Estimate, multiply and divide decimals" },
  { code: "9Nf.07", unit: "s9-u11", summary: "Direct and inverse proportion" },
  { code: "9Nf.08", unit: "s9-u11", summary: "Ratios and equivalence in a range of contexts" },
  // ---- Stage 9: Algebra ---------------------------------------------------
  { code: "9Ae.01", unit: "s9-u2", summary: "Laws of arithmetic applied to algebraic terms with integer powers" },
  { code: "9Ae.02", unit: "s9-u2", summary: "Expand two brackets, apply index laws, simplify algebraic fractions" },
  { code: "9Ae.03", unit: "s9-u2", summary: "Words to expressions and back, including squares, cubes and roots" },
  { code: "9Ae.04", unit: "s9-u2", summary: "Formulae with squares and cubes; change the subject" },
  { code: "9Ae.05", unit: "s9-u4", summary: "Form and solve equations, including an unknown in the denominator" },
  { code: "9Ae.06", unit: "s9-u4", summary: "Simultaneous linear equations, algebraically and graphically" },
  { code: "9Ae.07", unit: "s9-u4", summary: "Form and solve linear inequalities" },
  { code: "9As.01", unit: "s9-u9", summary: "Linear and quadratic sequences from patterns and term-to-term rules" },
  { code: "9As.02", unit: "s9-u9", summary: "nth term rules, linear and simple quadratic" },
  { code: "9As.03", unit: "s9-u9", summary: "Functions with indices: outputs, and inputs by inverse operations" },
  { code: "9As.04", unit: "s9-u10", summary: "Words to linear functions, y = mx + c or ax + by = c" },
  { code: "9As.05", unit: "s9-u10", summary: "Tables of values and graphs of linear (including implicit) and quadratic functions" },
  { code: "9As.06", unit: "s9-u10", summary: "Equation of a straight line, including fractional and negative gradients" },
  { code: "9As.07", unit: "s9-u11", summary: "Graphs and compound measures" },
  // ---- Stage 9: Geometry and measure --------------------------------------
  { code: "9Gg.01", unit: "s9-u7", summary: "Area and circumference of a circle" },
  { code: "9Gg.02", unit: "s9-u7", summary: "Very small and very large units of length, capacity and mass" },
  { code: "9Gg.03", unit: "s9-u7", summary: "Area of compound shapes from rectangles, triangles and circles" },
  { code: "9Gg.04", unit: "s9-u14", summary: "Volume of prisms and cylinders" },
  { code: "9Gg.05", unit: "s9-u14", summary: "Surface area of cubes, cuboids, prisms, pyramids and cylinders" },
  { code: "9Gg.06", unit: "s9-u14", summary: "Planes of reflective symmetry in 3D shapes" },
  { code: "9Gg.07", unit: "s9-u5", summary: "Sum of the interior angles of any polygon" },
  { code: "9Gg.08", unit: "s9-u5", summary: "Exterior angles of any polygon sum to 360°" },
  { code: "9Gg.09", unit: "s9-u5", summary: "Missing angles using lines, triangles and quadrilaterals" },
  { code: "9Gg.10", unit: "s9-u7", summary: "Pythagoras' theorem" },
  { code: "9Gg.11", unit: "s9-u5", summary: "Construct 60°, 45° and 30° angles and regular polygons" },
  { code: "9Gp.01", unit: "s9-u5", summary: "Bearings and scale on maps and plans" },
  { code: "9Gp.02", unit: "s9-u13", summary: "Points on a line segment from coordinates" },
  { code: "9Gp.03", unit: "s9-u13", summary: "Combinations of reflections, translations and rotations" },
  { code: "9Gp.04", unit: "s9-u13", summary: "Identify and describe a transformation or combination" },
  { code: "9Gp.05", unit: "s9-u13", summary: "Images under reflections, translations and rotations are congruent" },
  { code: "9Gp.06", unit: "s9-u13", summary: "Enlargement from a centre (inside, on or outside), positive integer scale factor" },
  { code: "9Gp.07", unit: "s9-u13", summary: "Effect of enlargement on perimeter and area of squares and rectangles" },
  // ---- Stage 9: Statistics and probability ---------------------------------
  { code: "9Ss.01", unit: "s9-u6", summary: "Choose data to collect; qualitative, quantitative, categorical, discrete, continuous" },
  { code: "9Ss.02", unit: "s9-u6", summary: "Bias and other issues in data collection and sampling" },
  { code: "9Ss.03", unit: "s9-u6", summary: "Record and represent data; choose a suitable representation" },
  { code: "9Ss.04", unit: "s9-u15", summary: "Compare distributions with averages and range, including grouped data" },
  { code: "9Ss.05", unit: "s9-u15", summary: "Interpret data; inferences and misleading information" },
  { code: "9Sp.01", unit: "s9-u12", summary: "Mutually exclusive events sum; all outcomes total 1" },
  { code: "9Sp.02", unit: "s9-u12", summary: "Independent and dependent successive events" },
  { code: "9Sp.03", unit: "s9-u12", summary: "Theoretical probability of combined events" },
  { code: "9Sp.04", unit: "s9-u12", summary: "Experiments: expected frequency compared with observed outcomes" },
];

export const objectivesFor = (unit: string) => framework.filter((objective) => objective.unit === unit);
